from .inf_administrasi import inf_administrasi_api
from .inf_dusun import inf_dusun_api
from .inf_penduduk import inf_penduduk_api
from .inf_perangkat import inf_perangkat_api
from .inf_sarana import inf_sarana_api
from .inf_umum import inf_umum_api
from .inf_unggulan import inf_unggulan_api
from .kartu_keluarga import kartu_keluarga_api
from .penduduk import penduduk_api
from .prog_desa import prog_desa_api
from .user import user_api
